version: '3.7'

services:
  zookeeper:
    platform: linux/amd64
    image: 'confluentinc/cp-zookeeper:latest'

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    platform: linux/amd64
    image: 'confluentinc/cp-kafka:7.1.0'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:29092'

  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
    volumes:
      - ./volumes/rabbitmq:/usr/share/rabbitmq/data
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data

  api:
    build: ./commatg_api
    command: python run.py
    ports:
      - '9000:9000'
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka

  bot:
    restart: always
    build: ./commatg_bot
    command: python run.py
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq

  celery:
    restart: always
    build: ./commatg_bot
    user: daemon
    command: celery -A src worker -l INFO --purge --pool=gevent
    depends_on:
      - bot
    environment:
      KAFKA_HOST: kafka
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
