version: '3.7'

services:

  commatg-api:
    build:
      context: /api
      dockerfile: commatg-api/Dockerfile
    image: commatg-api-image
    ports:
      - 9000:9000

  commatg-bot:
    build:
      context: /bot
      dockerfile: commatg-bot/Dockerfile
    image: commatg-bot-image

  zookeeper:
    platform: linux/amd64
    image: 'confluentinc/cp-zookeeper:latest'

    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - '22181:2181'

  kafka:
    platform: linux/amd64
    image: 'confluentinc/cp-kafka:7.1.0'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'

  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
    volumes:
      - ./volumes/rabbitmq:/usr/share/rabbitmq/data
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data
